package com.hemendra.comicreader.model.source;

public enum FailureReason {
    NOT_AVAILABLE_LOCALLY,
    ALREADY_LOADING,
    SOURCE_CLOSED,
    NETWORK_UNAVAILABLE,
    NETWORK_TIMEOUT,
    API_MISSING,
    CONTENT_MISSING,
    INVALID_RESPONSE_FROM_SERVER,
    UNKNOWN_LOCAL_ERROR,
    UNKNOWN_REMOTE_ERROR
}
